#!/usr/bin/env bash
#
# Moodsen
# ---------------------------------------------------------------------------
set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
    echo "Re-running with sudo ..."
    exec sudo -E bash "$0" "$@"
fi

echo "Setting up Moodsen ..."
echo "=========================="

SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
BACKEND_DIR="${REPO_ROOT}/back-end"
FRONTEND_DIR="${REPO_ROOT}/front-end"

if [[ ! -d "${BACKEND_DIR}" || ! -d "${FRONTEND_DIR}" ]]; then
    echo "ERROR: expected back-end/ and front-end/ under ${REPO_ROOT}" >&2
    exit 1
fi

log()  { echo -e "\n\033[1;34m==>\033[0m $*"; }
warn() { echo -e "\033[1;33mWARNING:\033[0m $*" >&2; }

if [[ -f "${SCRIPT_DIR}/deploy.env" ]]; then
    log "Loading config overrides from deploy/deploy.env"
    set -a; # shellcheck disable=SC1091
    source "${SCRIPT_DIR}/deploy.env"; set +a
fi

# --- Config (env-overridable) ---
APP_USER="${APP_USER:-$(stat -c '%U' "${REPO_ROOT}")}"
APP_GROUP="$(id -gn "${APP_USER}")"
API_WORKERS="${API_WORKERS:-2}"
APP_TIMEZONE="${APP_TIMEZONE:-Asia/Tehran}"
INSTALL_KAFKA="${INSTALL_KAFKA:-true}"

DB_NAME="${DB_NAME:-mohsen_mood_tracker}"
DB_USER="${DB_USER:-mohsen}"

APP_DOMAIN="${APP_DOMAIN:-}"
LETSENCRYPT_EMAIL="${LETSENCRYPT_EMAIL:-}"

KAFKA_VERSION="${KAFKA_VERSION:-3.9.0}"
SCALA_VERSION="${SCALA_VERSION:-2.13}"
KAFKA_HOME="/opt/kafka"

if [[ -n "${APP_DOMAIN}" && -n "${LETSENCRYPT_EMAIL}" ]]; then
    USE_TLS=true
    SCHEME=https
else
    USE_TLS=false
    SCHEME=http
fi

if [[ "${INSTALL_KAFKA}" == "true" ]]; then
    KAFKA_ENABLED=true
    KAFKA_SYSTEMD_DEP="kafka.service"
else
    KAFKA_ENABLED=false
    KAFKA_SYSTEMD_DEP=""
fi

run_as_user() { sudo -u "${APP_USER}" -H bash -c "$1"; }

# --- Secrets: generate once, then reuse on every subsequent run ---
SECRETS_FILE="/etc/moodsen/deploy.env"
mkdir -p /etc/moodsen
if [[ -f "${SECRETS_FILE}" ]]; then
    log "Reusing persisted secrets from ${SECRETS_FILE}"
    set -a; # shellcheck disable=SC1091
    source "${SECRETS_FILE}"; set +a
fi
: "${JWT_SECRET:=$(openssl rand -hex 32)}"
: "${DB_PASS:=$(openssl rand -hex 24)}"
cat > "${SECRETS_FILE}" <<EOF
# Persisted Moodsen secrets — generated by deploy/setup.sh. Keep private.
JWT_SECRET=${JWT_SECRET}
DB_PASS=${DB_PASS}
EOF
chmod 600 "${SECRETS_FILE}"

PUBLIC_HOST="${APP_DOMAIN:-$(hostname -f 2>/dev/null || hostname)}"
SITE_URL="${SCHEME}://${PUBLIC_HOST}"
if [[ "${USE_TLS}" == "true" ]]; then COOKIE_SECURE=true; else COOKIE_SECURE=false; fi

# ===========================================================================
log "Updating system packages ..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y

log "Installing base packages ..."
apt-get install -y \
    ca-certificates curl gnupg openssl \
    python3 python3-venv python3-pip python3-dev build-essential libffi-dev pkg-config libmariadb-dev \
    mariadb-server redis-server nginx

# --- Node.js 20 LTS (NodeSource) ---
if ! command -v node >/dev/null 2>&1; then
    log "Installing Node.js 20 LTS ..."
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    apt-get install -y nodejs
else
    log "Node.js already present: $(node --version)"
fi

# ===========================================================================
log "Configuring MariaDB (database '${DB_NAME}', user '${DB_USER}') ..."
systemctl enable --now mariadb

for _ in $(seq 1 30); do
    if mysqladmin ping >/dev/null 2>&1; then break; fi
    sleep 1
done

mysql <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
CREATE USER IF NOT EXISTS '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PASS}';
ALTER USER '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
ALTER USER '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL

# ===========================================================================
log "Enabling Redis ..."
systemctl enable --now redis-server

# ===========================================================================
if [[ "${KAFKA_ENABLED}" == "true" ]]; then
    log "Installing Kafka ${KAFKA_VERSION} (KRaft, single node) ..."
    apt-get install -y openjdk-17-jre-headless

    if [[ ! -x "${KAFKA_HOME}/bin/kafka-server-start.sh" ]]; then
        tarball="kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz"
        curl -fsSL "https://archive.apache.org/dist/kafka/${KAFKA_VERSION}/${tarball}" \
            -o "/tmp/${tarball}"
        tar -xzf "/tmp/${tarball}" -C /opt
        ln -sfn "/opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION}" "${KAFKA_HOME}"
        rm -f "/tmp/${tarball}"
    fi

    mkdir -p "${KAFKA_HOME}/data"
    cat > "${KAFKA_HOME}/config/moodsen-kraft.properties" <<EOF
process.roles=broker,controller
node.id=1
controller.quorum.voters=1@127.0.0.1:9093
listeners=PLAINTEXT://127.0.0.1:9092,CONTROLLER://127.0.0.1:9093
advertised.listeners=PLAINTEXT://127.0.0.1:9092
inter.broker.listener.name=PLAINTEXT
controller.listener.names=CONTROLLER
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
log.dirs=${KAFKA_HOME}/data
num.partitions=1
auto.create.topics.enable=true
offsets.topic.replication.factor=1
transaction.state.log.replication.factor=1
transaction.state.log.min.isr=1
EOF

    KAFKA_CLUSTER_ID="$("${KAFKA_HOME}/bin/kafka-storage.sh" random-uuid)"
    "${KAFKA_HOME}/bin/kafka-storage.sh" format \
        -t "${KAFKA_CLUSTER_ID}" \
        -c "${KAFKA_HOME}/config/moodsen-kraft.properties" \
        --ignore-formatted

    chown -R "${APP_USER}:${APP_GROUP}" "/opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION}" "${KAFKA_HOME}"

    cat > /etc/systemd/system/kafka.service <<EOF
[Unit]
Description=Apache Kafka (KRaft, Moodsen)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${APP_USER}
Group=${APP_GROUP}
Environment=KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
ExecStart=${KAFKA_HOME}/bin/kafka-server-start.sh ${KAFKA_HOME}/config/moodsen-kraft.properties
ExecStop=${KAFKA_HOME}/bin/kafka-server-stop.sh
Restart=on-failure
RestartSec=5
LimitNOFILE=100000

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable --now kafka

    log "Waiting for Kafka to accept connections ..."
    for _ in $(seq 1 60); do
        if "${KAFKA_HOME}/bin/kafka-topics.sh" --bootstrap-server 127.0.0.1:9092 --list >/dev/null 2>&1; then
            break
        fi
        sleep 2
    done

    log "Creating Kafka topics ..."
    for topic in moodsen.streak.updated moodsen.notification.requested moodsen.notification.dead-letter; do
        "${KAFKA_HOME}/bin/kafka-topics.sh" --bootstrap-server 127.0.0.1:9092 \
            --create --if-not-exists --topic "${topic}" \
            --partitions 1 --replication-factor 1 >/dev/null
    done
else
    warn "Kafka disabled (INSTALL_KAFKA=false)."
fi

# ===========================================================================
log "Writing back-end environment file ..."
cat > "${BACKEND_DIR}/.env" <<EOF
MARIADB_DATABASE=${DB_NAME}
MARIADB_USER=${DB_USER}
MARIADB_PASSWORD=${DB_PASS}
MARIADB_HOST=127.0.0.1
MARIADB_PORT=3306

JWT_SECRET=${JWT_SECRET}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=300

KAFKA_ENABLED=${KAFKA_ENABLED}
KAFKA_BOOTSTRAP_SERVERS=127.0.0.1:9092
KAFKA_STREAK_TOPIC=moodsen.streak.updated
KAFKA_NOTIFICATION_TOPIC=moodsen.notification.requested
KAFKA_NOTIFICATION_DLQ_TOPIC=moodsen.notification.dead-letter

REDIS_URL=redis://127.0.0.1:6379/0
NOTIFICATION_CACHE_TTL_SECONDS=60

FRONTEND_ORIGIN=${SITE_URL}
COOKIE_SECURE=${COOKIE_SECURE}

STREAK_MILESTONE_DAYS=7
APP_TIMEZONE=${APP_TIMEZONE}
EOF
chown "${APP_USER}:${APP_GROUP}" "${BACKEND_DIR}/.env"
chmod 600 "${BACKEND_DIR}/.env"

log "Configuring Python virtual environment & dependencies ..."
run_as_user "cd '${BACKEND_DIR}' && \
    ([[ -d venv ]] || python3 -m venv venv) && \
    ./venv/bin/pip install --upgrade pip && \
    ./venv/bin/pip install -r requirements.txt"

log "Applying database migrations ..."
if ! run_as_user "cd '${BACKEND_DIR}' && ./venv/bin/alembic upgrade head"; then
    warn "alembic failed; the app also creates tables on startup, continuing."
fi

# ===========================================================================
log "Building Next.js front-end ..."
cat > "${FRONTEND_DIR}/.env.production.local" <<EOF
NEXT_PUBLIC_API_BASE=/api
EOF
chown "${APP_USER}:${APP_GROUP}" "${FRONTEND_DIR}/.env.production.local"

if [[ -f "${FRONTEND_DIR}/package-lock.json" ]]; then
    run_as_user "cd '${FRONTEND_DIR}' && npm ci"
else
    run_as_user "cd '${FRONTEND_DIR}' && npm install"
fi
run_as_user "cd '${FRONTEND_DIR}' && NEXT_PUBLIC_API_BASE=/api npm run build"

# ===========================================================================
log "Installing systemd services ..."

cat > /etc/systemd/system/moodsen-api.service <<EOF
[Unit]
Description=Moodsen API (FastAPI / uvicorn)
After=network-online.target mariadb.service redis-server.service ${KAFKA_SYSTEMD_DEP}
Wants=network-online.target

[Service]
Type=simple
User=${APP_USER}
Group=${APP_GROUP}
WorkingDirectory=${BACKEND_DIR}
EnvironmentFile=${BACKEND_DIR}/.env
ExecStart=${BACKEND_DIR}/venv/bin/uvicorn app.main:app --host 127.0.0.1 --port 8000 --workers ${API_WORKERS}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

cat > /etc/systemd/system/moodsen-worker.service <<EOF
[Unit]
Description=Moodsen notification worker (APScheduler + Kafka consumers)
After=network-online.target mariadb.service redis-server.service ${KAFKA_SYSTEMD_DEP}
Wants=network-online.target

[Service]
Type=simple
User=${APP_USER}
Group=${APP_GROUP}
WorkingDirectory=${BACKEND_DIR}
EnvironmentFile=${BACKEND_DIR}/.env
ExecStart=${BACKEND_DIR}/venv/bin/python -m app.workers.notification_worker
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

cat > /etc/systemd/system/moodsen-web.service <<EOF
[Unit]
Description=Moodsen front-end (Next.js)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${APP_USER}
Group=${APP_GROUP}
WorkingDirectory=${FRONTEND_DIR}
Environment=NODE_ENV=production
Environment=PORT=3000
Environment="PATH=/usr/bin:/usr/local/bin:/bin"
ExecStart=/usr/bin/npm run start
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now moodsen-api moodsen-worker moodsen-web

# ===========================================================================
log "Configuring Nginx reverse proxy ..."
cat > /etc/nginx/sites-available/moodsen <<EOF
server {
    listen 80;
    server_name ${PUBLIC_HOST};

    client_max_body_size 10m;

    location /api/ {
        proxy_pass http://127.0.0.1:8000/;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Connection "";
        proxy_buffering off;
        proxy_cache off;
        chunked_transfer_encoding off;
        proxy_read_timeout 86400s;
    }

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

ln -sfn /etc/nginx/sites-available/moodsen /etc/nginx/sites-enabled/moodsen
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl enable --now nginx
systemctl reload nginx

# ===========================================================================
if [[ "${USE_TLS}" == "true" ]]; then
    log "Requesting Let's Encrypt certificate for ${APP_DOMAIN} ..."
    apt-get install -y certbot python3-certbot-nginx
    if certbot --nginx -d "${APP_DOMAIN}" \
        --non-interactive --agree-tos -m "${LETSENCRYPT_EMAIL}" --redirect; then
        log "HTTPS enabled."
    else
        warn "certbot failed. Site is still reachable over HTTP; re-run once DNS"
        warn "for ${APP_DOMAIN} points at this instance."
    fi
fi

log "Done."
cat <<EOF

  Moodsen is deployed.

    URL:        ${SITE_URL}
    API health: ${SITE_URL}/api/health
    App user:   ${APP_USER}
    Kafka:      ${KAFKA_ENABLED}

  Services:
    systemctl status moodsen-api moodsen-worker moodsen-web
    journalctl -u moodsen-api -f
    journalctl -u moodsen-worker -f

  Secrets are stored in ${SECRETS_FILE}.
EOF
